version: '3.9'

networks:
  ft_transcendence:
    driver: bridge

services:
  frontend:
    build: requirements/frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ft_transcendence
    hostname: frontend
  
  backend:
    build: requirements/backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - ft_transcendence
    hostname: backend