version: '3.9'

networks:
  ft_transcendence:
    driver: bridge

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ft_transcendence
    #env_file: .env

  frontend:
    build: requirements/frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - ft_transcendence
    #env_file: .env